# Generated by Django 6.0.4 on 2026-04-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_date_changed_user_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
