# Generated by Django 6.0.4 on 2026-04-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_craeted_at_address_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
